name: CHANNEL_A_DEPLOY

on: 
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    username:
      description: 'A username passed from the caller workflow'
      required: true
      type: string


jobs:
  release:
    name: Deploy_A_TEST
    runs-on: ubuntu-latest

    steps:
    - name: deploy test
      run: |
        echo "CHANNEL_TYPE: ${{ github.event.inputs.channel_type }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "test: ${{ inputs.tag }}"
        echo "test2: ${{ inputs.username }}"
