name: CHANNEL_B_DEPLOY

on: 
  workflow_call:
    inputs:
      channel_type:
        description: '배포 채널'
        type: string
        required: true

jobs:
  release:
    name: Deploy_A_TEST
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy test1
        uses: actions/checkout@v3

      - name: deploy test
        run: |
          echo "CHANNEL_TYPE: $CHANNEL_TYPE"
          echo "Environment: $ENVIRONMENT"
