name: CHANNEL_B_DEPLOY

on: 
  workflow_call:
    inputs:
      environment:
        description: '배포 환경'
        required: true
        type: string
jobs:
  release:
    name: Deploy_B_TEST
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy test
        run: |
          echo "CHANNEL_TYPE: ${{ github.event.inputs.channel_type }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
