name: CHANNEL_A_DEPLOY

on: 
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string

jobs:
  release:
    name: Deploy_A_TEST
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy test
        run: |
          echo "CHANNEL_TYPE: ${{ github.event.inputs.channel_type }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "test: ${{ inputs.release-tag }}"
