name: "Deployment Dispatcher"

on:
  workflow_dispatch:
    inputs:
      channel_type:
        description: '배포 채널'
        required: true
        type: choice
        options:
          - CHANNEL_A
          - CHANNEL_B
      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - development
          - staging
          - qa
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Environment Validation
        run: |
          CHANNEL="${{ github.event.inputs.channel_type }}"
          ENVIRONMENT="${{ github.event.inputs.environment }}"
           
          if [ "$ENVIRONMENT" == "qa" ] && [ "$CHANNEL" == "CHANNEL_A" ]; then
            echo "Invalid combination: CHANNEL_A cannot use QA environment."
            exit 1          
          fi
          
          if [ "$ENVIRONMENT" == "staging" ] && [ "$CHANNEL" == "CHANNEL_B" ]; then
            echo "Invalid combination: CHANNEL_B cannot use Staging environment."
            exit 1          
          fi
          
           echo "CHANNEL=$CHANNEL" >> $GITHUB_ENV
           echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

      - name: Create GitHub Tag and Release
        run: |
          if [ "$ENVIRONMENT" == 'development' ]; then
            TAG_NAME="release-dev"
          elif [ "$ENVIRONMENT" == 'qa' ]; then
            TAG_NAME="release-qa"
          elif [ "$ENVIRONMENT" == 'staging' ]; then
            TAG_NAME="release-staging"
          elif [ "$ENVIRONMENT" == 'production' ]; then
            TIMESTAMP=$(date -u "Y%m%d%H%M%S%Z")
            TAG_NAME="release-prod-v$TIMESTAMP"
          else
            echo "Invalid environment specified."
            exit 1
          fi
          
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create GitHub Tag and Release2
        run: |
          echo "TAG_NAME: $TAG_NAME"

      - name: Create GitHub Tag and Release3
        run: |
          git tag $TAG_NAME
          
          if [ "$ENVIRONMENT" == 'production' ]; then
            git push origin $TAG_NAME
            gh release create $TAG_NAME -t "$TAG_NAME" -n "Release notes for $TAG_NAME"
          else
            git push origin "$TAG_NAME" --force 
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: |
          echo "ref_name : $GITHUB_REF_NAME"
          echo "SHORT_SHA=${GITHUB_SHA:0:6}"
          echo "TAG_NAME=$TAG_NAME"

  channel:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Tag and Release2
        run: |
          echo "inputs.channel_type: ${{ github.event.inputs.channel_type }}"
          echo "inputs.channel_type: ${{ inputs.channel_type }}"

#    if: ${{ inputs.channel_type }} == 'CHANNEL_A'
#    run: |
#      echo " : ${{ inputs.channel_type }}"
#    uses: ./.github/workflows/channel_a.yaml
