name: "Deployment Dispatcher"

on:
  workflow_dispatch:
    inputs:
      channel_type:
        description: '배포 채널'
        required: true
        type: choice
        options:
          - CHANNEL_A
          - CHANNEL_B
      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - development
          - staging
          - qa
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Validation
        run: |
          CHANNEL="${{ github.event.inputs.channel_type }}"
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          
          if [ "$ENVIRONMENT" == "qa" ] && [ "$CHANNEL" == "CHANNEL_A" ]; then
            echo "Invalid combination: CHANNEL_A cannot use QA environment."
            exit 1          
          fi
          
          if [ "$ENVIRONMENT" == "staging" ] && [ "$CHANNEL" == "CHANNEL_B" ]; then
            echo "Invalid combination: CHANNEL_B cannot use Staging environment."
            exit 1          
          fi
    
  
          
           



