name: "Deployment Dispatcher"

on:
  workflow_dispatch:
    inputs:
      channel_type:
        description: '배포 채널'
        required: true
        type: choice
        options:
          - CHANNEL_A
          - CHANNEL_B
      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - development
          - staging
          - qa
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Validation
        run: |
          CHANNEL="${{ github.event.inputs.channel_type }}"
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          
          if [ "$ENVIRONMENT" == "qa" ] && [ "$CHANNEL" == "CHANNEL_A" ]; then
            echo "Invalid combination: CHANNEL_A cannot use QA environment."
            exit 1          
          fi
          
          if [ "$ENVIRONMENT" == "staging" ] && [ "$CHANNEL" == "CHANNEL_B" ]; then
            echo "Invalid combination: CHANNEL_B cannot use Staging environment."
            exit 1          
          fi

      - name: Create GitHub Tag and Release
        run: |
          if [ "${{ github.event.inputs.environment }}" == 'development' ]; then
            TAG_NAME="release-dev"
          elif [ "${{ github.event.inputs.environment }}" == 'qa' ]; then
            TAG_NAME="release-qa"
          elif [ "${{ github.event.inputs.environment }}" == 'staging' ]; then
            TAG_NAME="release-staging"
          elif [ "${{ github.event.inputs.environment }}" == 'production' ]; then
            TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            TAG_NAME="release-prod-$TIMESTAMP"
          else
            echo "Invalid environment specified."
            exit 1
          fi
          
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create GitHub Tag and Release2
        run: |
          echo "TAG_NAME: $TAG_NAME"

  
          
           



