name: "Deployment Dispatcher"

on:
  workflow_dispatch:
    inputs:
      channel_type:
        description: '배포 채널'
        required: true
        type: choice
        options:
          - CHANNEL_A
          - CHANNEL_B
      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - development
          - staging
          - qa
          - production

jobs:
  deploy:
    uses: ./.github/workflows/create_release.yml

  log:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: logging
        run: |
          echo "release-tag: ${{ needs.deploy.outputs.release-tag }}"

  deply_channel_a:
    needs: deploy
    if: ${{ github.event.inputs.channel_type == 'CHANNEL_A'}}
    uses: ./.github/workflows/channel_a.yaml
    with:
      release-tag: ${{ needs.deploy.outputs.release-tag }}

  deploy_channel_b:
    needs: deploy
    if: ${{ github.event.inputs.channel_type == 'CHANNEL_B'}}
    uses: ./.github/workflows/channel_b.yml
    with:
      release-tag: ${{ needs.deploy.outputs.release-tag }}

  log2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: logging
        run: |
          echo "release-tag: ${{ needs.deploy.outputs.release-tag }}"

