name: "Deployment Dispatcher"

on:
  workflow_dispatch:
    inputs:
      channel_type:
        description: '배포 채널'
        required: true
        type: choice
        options:
          - CHANNEL_A
          - CHANNEL_B
      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: deploy test
        run: |
          echo "CHANNEL_TYPE: $CHANNEL_TYPE"
          echo "Environment: $ENVIRONMENT"
        env:
          CHANNEL_TYPE: ${{ inputs.channel_type }}
          ENVIRONMENT: ${{ inputs.environment }}
      - if: ${{ inputs.channel_type }} == "CHANNEL_A"
        run: |
          echo "CHANNEL_TYPE: $CHANNEL_A"
          echo "Environment: $ENVIRONMENT"
        env:
          CHANNEL_TYPE: ${{ inputs.channel_type }}
          ENVIRONMENT: ${{ inputs.environment }}
      - if: ${{ inputs.channel_type }} == "CHANNEL_B"
        run: |
          echo "CHANNEL_TYPE: $CHANNEL_B"
          echo "Environment: $ENVIRONMENT"
