name: "Deployment Dispatcher"

on:
  workflow_dispatch:
    inputs:
      channel_type:
        description: '배포 채널'
        required: true
        type: choice
        options:
          - CHANNEL_A
          - CHANNEL_B
      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  release:
    name: Deploy
    uses: ./.github/workflows/channel_b.yaml
    with:
      channel_type: ${{ inputs.channel_type }}
